# GT System
version: "3.8"

networks:
  db:
    external: true
    name: ${DB_NET}
  ingress:
    external: true
    name: ${INGRESS_NET}
volumes:
  sftp:
  ssh_vol:
    external: true

services:
  meteor:
    image: ${GTS_IMAGE}
    deploy:
      placement:
        constraints:
          - node.labels.${NODE_LABEL} == 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=${INGRESS_NET}
        - traefik.constraint-label=${INGRESS_NET}
        - traefik.http.routers.${NAME}-meteor-http.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.${NAME}-meteor-http.entrypoints=http
        - traefik.http.routers.${NAME}-meteor-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-meteor-https.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.${NAME}-meteor-https.entrypoints=https
        - traefik.http.routers.${NAME}-meteor-https.tls=true
        - traefik.http.routers.${NAME}-meteor-https.tls.certresolver=le
        - traefik.http.services.${NAME}-meteor.loadbalancer.server.port=${GTS_PORT}

    environment:
      MONGO_URL: ${MONGO_URL}
      ROOT_URL: "https://${DOMAIN}"
      EXACT_NODE_VERSION: "true"
      NODE_VERSION: "${NODE_VERSION}"
      METEOR_SETTINGS: ${METEOR_SETTINGS}
    networks:
      - db
      - ingress
  sftp:
    image: writl/sftp
    deploy:
      placement:
        constraints:
          - node.labels.${NODE_LABEL} == 1    
    volumes:
      - sftp:/data/incoming
      - ssh_vol:/ssh
    ports:
      - ${SFTP_PORT}:22
    networks:
      - db
    environment:
      - USER:${SFTP_USER}
      - PASS=${SFTP_PASS}
      - USER_ID=33
      - GROUP_ID=33

